ci(vuln.yml): add grype scan, fix conditional fail
add more debug info

diff --git a/.github/workflows/vuln.yml b/.github/workflows/vuln.yml
--- a/.github/workflows/vuln.yml
+++ b/.github/workflows/vuln.yml
@@ -26,6 +26,18 @@ jobs:
           tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:vuln
           use-docker-mediatypes: false
           archs: x86_64,aarch64
+      - name: docker load
+        run: |
+          docker load < output.tar
+      - name: grype scan
+        id: grype-scan
+        uses: anchore/scan-action@ecfd0e98932e57ea8f68f29c4f418fc41a8194db
+        with:
+          image: output.tar
+          fail-build: false
+          severity-cutoff: low
+      - name: cat grype scan
+        run: cat "${{ steps.grype-scan.outputs.sarif }}" | jq .
       - name: trivy scan
         uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252
         with:
@@ -35,36 +47,41 @@ jobs:
           exit-code: 0
           vuln-type: 'os,library'
           severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
+      - name: cat trivy scan
+        run: cat trivy-results.sarif | jq .
       - name: install cosign
         uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b
       # compare cve from latest image (ghcr.io/andros21/pandoc-slides:latest)
       # and job apko compiled image (output.tar)
       #
-      # fail only if "now cve" > "latest cve" (trivy only)
+      # fail only if "now cve" > "latest cve"
       - name: cve count
         env:
           COSIGN_EXPERIMENTAL: 1
         run: |
           set -x
-          CVE_LOCAL_COUNT=-1
-          CVE_LATEST_COUNT=-1
-          CVE_LOCAL_COUNT=$(cat trivy-results.sarif \
-            | jq '.predicate.scanner.result.runs[0].results | length')
-          CVE_LATEST_COUNT=$(cosign download attestation ${REGISTRY}/${IMAGE_NAME}:latest \
-            | head -1 \
+          CVE_LOCAL_COUNT=(-1 -1)
+          CVE_LATEST_COUNT=(-1 -1)
+          CVE_LOCAL_COUNT[0]=$(cat trivy-results.sarif \
+            | jq '.runs[0].results | length')
+          CVE_LOCAL_COUNT[1]=$(cat cat ${{ steps.grype-scan.outputs.sarif }} \
+            | jq '.runs[0].results | length')
+          CVE_LATEST_COUNT=($(cosign download attestation ${REGISTRY}/${IMAGE_NAME}:latest \
             | jq -r .payload | base64 -d \
-            | jq '.predicate.scanner.result.runs[0].results | length')
+            | jq '.predicate.scanner.result.runs[0].results | length' | xargs))
           # stdout job summary
-          echo "TRIVY_COUNT: ${CVE_LOCAL_COUNT} vs ${CVE_LATEST_COUNT}"
+          echo "TRIVY_COUNT: ${CVE_LOCAL_COUNT[0]} vs ${CVE_LATEST_COUNT[0]}"
+          echo "GRYPE_COUNT: ${CVE_LOCAL_COUNT[1]} vs ${CVE_LATEST_COUNT[1]}"
           # markdown job summary
           echo "### Check vulnerabilities summary" >> $GITHUB_STEP_SUMMARY
           echo >> $GITHUB_STEP_SUMMARY
-          echo "|        |  TRIVY  |" >> $GITHUB_STEP_SUMMARY
-          echo "|--------|:-------:|" >> $GITHUB_STEP_SUMMARY
-          echo "| local  |  ${CVE_LOCAL_COUNT}  |" >> $GITHUB_STEP_SUMMARY
-          echo "| latest |  ${CVE_LATEST_COUNT} |" >> $GITHUB_STEP_SUMMARY
+          echo "|        |  TRIVY  |  GRYPE  |" >> $GITHUB_STEP_SUMMARY
+          echo "|--------|:-------:|:-------:|" >> $GITHUB_STEP_SUMMARY
+          echo "| local  |  ${CVE_LOCAL_COUNT[0]}  | ${CVE_LOCAL_COUNT[1]} |" >> $GITHUB_STEP_SUMMARY
+          echo "| latest |  ${CVE_LATEST_COUNT[0]} | ${CVE_LATEST_COUNT[1]} |" >> $GITHUB_STEP_SUMMARY
           echo >> $GITHUB_STEP_SUMMARY
           # job fail logic
           [ ${CVE_LOCAL_COUNT[0]} -ge ${CVE_LATEST_COUNT[0]} ] && [ ${CVE_LOCAL_COUNT[1]} -ge ${CVE_LATEST_COUNT[1]} ] \
-            || echo "#### pandoc-slides image insecure :x:" >> $GITHUB_STEP_SUMMARY
+            || (echo "#### pandoc-slides image insecure :x:" >> $GITHUB_STEP_SUMMARY \
+            && exit 1)
           echo "#### pandoc-slides image secure :heavy_check_mark:" >> $GITHUB_STEP_SUMMARY
